package com.yandex.app.service;

public enum Endpoint {
    GET_TASKS,
    GET_TASK,
    GET_EPICS,
    GET_EPIC,
    GET_SUBTASKS,
    GET_SUBTASK,
    POST_TASK,
    POST_EPIC,
    POST_SUBTASK,
    DELETE_TASK,
    DELETE_EPIC,
    DELETE_SUBTASK,
    DELETE_TASKS,
    DELETE_EPICS,
    DELETE_SUBTASKS,
    GET_EPIC_SUBTASKS,
    GET_HISTORY,
    GET_PRIORITIZED,
    GET_TASK_KEY,
    POST_UPDATE_TASK,
    POST_UPDATE_EPIC,
    POST_UPDATE_SUBTASK,
    POST_TASK_DATE,
    POST_SUBTASK_DATE,
    UNKNOWN
}
